#!/usr/bin/env bash
# =============================================================================
# Powerhouse VPS Deployment Script
# Usage: bash deploy_vps.sh [VPS_IP] [SSH_USER]
# Example: bash deploy_vps.sh 144.126.146.8 root
# =============================================================================
set -euo pipefail

VPS_IP="${1:-}"
SSH_USER="${2:-root}"
REPO_DIR="/opt/powerhouse"
BRANCH="claude/harden-powerhouse-architecture-Oyi0C"

# --- Colours ---
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# --- Validate args ---
[[ -z "$VPS_IP" ]] && error "Usage: $0 <VPS_IP> [SSH_USER]"

SSH="ssh -o StrictHostKeyChecking=no ${SSH_USER}@${VPS_IP}"
SCP="scp -o StrictHostKeyChecking=no"

info "Target: ${SSH_USER}@${VPS_IP}"

# =============================================================================
# STEP 1 — Install Docker on VPS
# =============================================================================
info "Step 1/5 — Installing Docker..."
$SSH bash -s <<'REMOTE'
set -euo pipefail
if command -v docker &>/dev/null; then
    echo "Docker already installed: $(docker --version)"
else
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com | bash
    systemctl enable docker
    systemctl start docker
    echo "Docker installed: $(docker --version)"
fi

if docker compose version &>/dev/null 2>&1; then
    echo "Docker Compose (plugin) available"
elif command -v docker-compose &>/dev/null; then
    echo "docker-compose available"
else
    echo "Installing Docker Compose plugin..."
    apt-get install -y docker-compose-plugin 2>/dev/null || \
    curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" \
        -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
fi
REMOTE

# =============================================================================
# STEP 2 — Clone / update repo on VPS
# =============================================================================
info "Step 2/5 — Syncing repository..."
$SSH bash -s <<REMOTE
set -euo pipefail
if [ -d "$REPO_DIR/.git" ]; then
    echo "Repo exists — pulling latest..."
    cd $REPO_DIR
    git fetch origin
    git checkout $BRANCH
    git pull origin $BRANCH
else
    echo "Cloning repo..."
    git clone --branch $BRANCH \
        https://github.com/richter83-star/Powerhouse-platform.git $REPO_DIR || \
    { echo "GitHub clone failed — you may need to push to GitHub or copy files manually."; exit 1; }
fi
echo "Repo ready at $REPO_DIR"
REMOTE

# =============================================================================
# STEP 3 — Create .env if it doesn't exist
# =============================================================================
info "Step 3/5 — Configuring environment..."
$SSH bash -s <<'REMOTE'
set -euo pipefail
ENV_FILE="/opt/powerhouse/.env"
if [ -f "$ENV_FILE" ]; then
    echo ".env already exists — skipping auto-generation."
else
    echo "Generating .env with random secrets..."
    PG_PASS=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 32)
    REDIS_PASS=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 32)
    SECRET_KEY=$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 64)
    JWT_SECRET=$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 64)
    NEXTAUTH_SECRET=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)

    cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy_vps.sh — edit as needed
DEBUG=False
POSTGRES_USER=powerhouse_user
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=powerhouse
REDIS_PASSWORD=${REDIS_PASS}
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
MARKETPLACE_CURRENCY=usd
SENTRY_DSN=
SENTRY_ENVIRONMENT=production
LOG_FORMAT=json
ENABLE_FILE_LOGGING=true
NEXT_PUBLIC_API_URL=http://$(hostname -I | awk '{print $1}'):8001
S3_BUCKET=
S3_REGION=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
EOF
    echo ".env created. Secrets auto-generated."
    echo ""
    echo "  PostgreSQL password : ${PG_PASS}"
    echo "  Redis password      : ${REDIS_PASS}"
    echo ""
    echo "Save these — they are stored in /opt/powerhouse/.env"
fi
REMOTE

# =============================================================================
# STEP 4 — Build & start containers
# =============================================================================
info "Step 4/5 — Building and starting containers..."
$SSH bash -s <<'REMOTE'
set -euo pipefail
cd /opt/powerhouse

# Pick docker compose command
if docker compose version &>/dev/null 2>&1; then
    DC="docker compose"
else
    DC="docker-compose"
fi

echo "Pulling base images..."
$DC pull postgres redis 2>/dev/null || true

echo "Building application images..."
$DC build --parallel

echo "Starting all services..."
$DC up -d

echo "Waiting for services to be healthy (up to 60s)..."
for i in $(seq 1 12); do
    sleep 5
    RUNNING=$($DC ps --status running --quiet 2>/dev/null | wc -l || echo 0)
    echo "  [${i}/12] Running containers: ${RUNNING}"
    if [ "$RUNNING" -ge 4 ]; then
        break
    fi
done
REMOTE

# =============================================================================
# STEP 5 — Health check
# =============================================================================
info "Step 5/5 — Running health check..."
$SSH bash -s <<REMOTE
set -euo pipefail
echo "Container status:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep powerhouse || true

echo ""
echo "Testing backend health endpoint..."
for i in 1 2 3 4 5; do
    if curl -sf http://localhost:8001/health > /dev/null 2>&1; then
        echo "  Backend health: OK"
        break
    fi
    echo "  Attempt \$i/5 — waiting..."
    sleep 6
done

echo ""
echo "Testing frontend..."
if curl -sf http://localhost:3000 > /dev/null 2>&1; then
    echo "  Frontend: OK"
else
    echo "  Frontend: not yet ready (may still be starting)"
fi
REMOTE

# =============================================================================
# Done
# =============================================================================
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  Powerhouse deployed successfully!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "  Frontend  : ${YELLOW}http://${VPS_IP}:3000${NC}"
echo -e "  Backend   : ${YELLOW}http://${VPS_IP}:8001${NC}"
echo -e "  API Docs  : ${YELLOW}http://${VPS_IP}:8001/docs${NC}"
echo ""
echo -e "  Manage    : ssh ${SSH_USER}@${VPS_IP}"
echo -e "  Logs      : docker compose -C /opt/powerhouse logs -f"
echo -e "  Stop      : docker compose -C /opt/powerhouse down"
echo -e "  Restart   : docker compose -C /opt/powerhouse restart"
echo ""
